### ISSUE TITLE
好友功能

### ISSUE THREAD

**Issue by YunMengqianyi** [Type-Shift-Arena/Type-Shift-Arena-Frontend#7]
![image](https://github.com/user-attachments/assets/6a2cc4a6-daf6-4b63-b724-f36c56a1c2da)
friends为好友列表
![image](https://github.com/user-attachments/assets/c82575c0-60b3-443c-b1ca-40ac8fe883ca)
getFriends接口返回数据：
![image](https://github.com/user-attachments/assets/3a0bb7a6-ba3a-463b-ade4-8fa6afa3c512)
个人后端测试js代码供参考
![image](https://github.com/user-attachments/assets/c6dbec2b-10bc-4940-8a62-c643fb7139de)
searchFriend接口返回数据：
![image](https://github.com/user-attachments/assets/23226fa8-608a-433f-933a-fc90f840529c)
后端代码参考
![image](https://github.com/user-attachments/assets/e81c8d15-9fdd-4a49-806a-2fd62a1c0500)
addFriend接口返回数据
![image](https://github.com/user-attachments/assets/5be02f5b-ee48-4c9e-8a40-2bc8db531f01)
c后端代码参考
![image](https://github.com/user-attachments/assets/cc4b817d-c8e9-4bc2-9091-f12a337db8ff)

**Comment by hiddenSharp429** [comment]
Copy

**Comment by hiddenSharp429** [comment]
@YueMingju

**Comment by hiddenSharp429** [comment]
已经开发好了，详情请看PR
https://github.com/Type-Shift-Arena/Type-Shift-Arena-Backend/pull/15
你在issue中所提到的接口均可以在swaager UI中进行测试以及调试
![image](https://github.com/user-attachments/assets/65ef1d5b-c938-4d24-a1ac-29af75417606)
